services:
  postgres:
    platform: linux/amd64
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=maindb #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      
  pgadmin:
    platform: linux/amd64
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=abhijit.shingote@zelis.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:5050"
    restart: always

  flaskapp:
    platform: linux/amd64
    container_name: flaskapp
    build: .
    ports: 
      - "80:80"
      - "8900:8900"
    volumes: 
      - .:/app
